[package]
authors = ["Aaronepower <theaaronepower@gmail.com>"]
build = "src/lib/build.rs"
description = "A program that allows you to count code, quickly."
homepage = "https://aaronepower.github.io/tokei/"
include = ["src/**/*", "cli.yml", "Cargo.toml", "LICENCE-APACHE", "LICENCE-MIT"]
license = "MIT/Apache-2.0"
name = "tokei"
readme = "README.md"
repository = "https://github.com/Aaronepower/tokei.git"
version = "4.4.0"

[[bin]]
doc = false
name = "tokei"
path = "src/main.rs"

[build-dependencies]
serde = "~0.8.0"
serde_json = "~0.8.0"

[build-dependencies.handlebars]
features = ["serde_type"]
version = "0.21.1"

[build-dependencies.serde_codegen]
optional = true
version = "0.8.0"

[dependencies]
encoding = "0.2.33"
glob = "~0.2.11"
lazy_static = "0.2.1"
log = "0.3.6"
maplit = "~0.1.3"
memmap = "0.5.0"
rayon = "=0.4.2"
regex = "0.1.80"
walkdir = "~0.1.5"

[dependencies.clap]
features = ["yaml"]
version = "~2.10.0"

[dependencies.env_logger]
features = []
version = "~0.3.5"

[dependencies.rustc-serialize]
optional = true
version = "~0.3.19"

[dependencies.serde]
optional = true
version = "~0.8.0"

[dependencies.serde_cbor]
optional = true
version = "~0.3.3"

[dependencies.serde_json]
optional = true
version = "~0.8.0"

[dependencies.serde_yaml]
optional = true
version = "~0.4.0"

[dependencies.toml]
default-features = false
features = ["serde"]
optional = true
version = "~0.2.0"

[dev-dependencies]
tempdir = "~0.3.5"

[features]
all = ["json", "cbor", "toml-io", "yaml"]
cbor = ["io", "rustc-serialize", "serde_cbor"]
default = []
io = ["serde_codegen", "serde"]
json = ["io", "serde_json"]
toml-io = ["io", "toml/serde"]
yaml = ["io", "serde_yaml"]

[lib]
name = "tokei"
path = "src/lib/lib.rs"

[profile]

[profile.release]
debug = true
